source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'lingke' do
    pod 'AFNetworking'
    pod 'MBProgressHUD'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'SSKeychain'
    pod 'Bugtags', '~> 1.1.9' 
end
